language: objective-c

before_install:
  - brew update
  - brew install xctool

branches:
  only:
    - develop

notifications:
  email: false

script: xctool ONLY_ACTIVE_ARCH=NO -workspace PPiAwesomeButton-Demo/PPiAwesomeButton-Demo.xcworkspace -scheme PPiAwesomeButton-Demo build test -sdk iphonesimulator
