language: objective-c
xcode_sdk: iphonesimulator
rvm: 1.9.3

before_install:
  - cd PPiAwesomeButton-Demo
  - gem install --no-rdoc --no-ri cocoapods
  - gem install --no-rdoc --no-ri pr-changelog xcpretty
  - pod install
script:
  - xctool -workspace PPiAwesomeButton-Demo.xcworkspace -scheme PPiAwesomeButton-Demo build -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
